### ISSUE TITLE
Error when closing the plug-in

### ISSUE THREAD

**Issue by Dragoy** [PeachScript/sketch-plugin-monster#12]
Screencast error: http://take.ms/y6bzo
Log error: http://pastebin.com/VKsRuuiQ

**Comment by PeachScript** [comment]
Thanks for your screencast and crash log!

I try to fix this issue by the referenced commit, but I'm not sure it is effective, if you can, please help me to test the [latest source code](https://github.com/PeachScript/sketch-plugin-monster/archive/master.zip) in your computer, thanks again!

**Comment by Dragoy** [comment]
Now everything is working. 
Thank you ❤️

**Comment by PeachScript** [comment]
That's great! I plan to include this fix into the next milestone version [`v0.2.0`](https://github.com/PeachScript/sketch-plugin-monster/milestone/2), thank you very much 😄
