### ISSUE TITLE
Support for longer shortcuts

### ISSUE THREAD

**Issue by RaphyRaph** [PeachScript/sketch-plugin-monster#14]
In the screenshot below, some of my shortcuts are 4 characters long.

![image](https://cloud.githubusercontent.com/assets/3810802/23358993/da44b2ac-fcec-11e6-91c8-39adc578f3d1.png)

**Comment by PeachScript** [comment]
Yep, it is already in the plan, thanks!

I will release the next milestone version [v0.2.0](https://github.com/PeachScript/sketch-plugin-monster/milestone/2) this week, contains this problem :P.

**Comment by RaphyRaph** [comment]
0.2.0 is a huge improvement!

**Comment by PeachScript** [comment]
@RaphyRaph Glad you love it! Please tell me if you have any idea for improvements 😄
