### ISSUE TITLE
Shortcuts aren't populating in plugin UI

### ISSUE THREAD

**Issue by lostmonster** [PeachScript/sketch-plugin-monster#18]
![screen shot 2017-03-20 at 2 59 07 pm](https://cloud.githubusercontent.com/assets/18298999/24123722/ecb48146-0d7d-11e7-874e-7e0bbd8f8a7c.png)

See above. The shortcuts I've assigned to Top, Left, Right, Bottom do not populate in your plugin. 

Additionally, I cannot resize the window of the UI.

**Comment by PeachScript** [comment]
How did you assigned shortcuts for the Top, Left, Right and Bottom? Manually or use this plugin?

And this plugin does not support resize window currently.

**Comment by lostmonster** [comment]
Those shortcuts for top right left bottom were custom assigned before I found out about your plugin.

**Comment by PeachScript** [comment]
I guess the following two possibilities:
1. I missing some way to set shortcuts in `Sketch`, so this plugin cannot detect your shortcuts;
2. Your plugins directory has multiple `Sketch Guides.sketchplugin` files, `Sketch` and this plugin detected different file.
