### ISSUE TITLE
Check for custom shortcuts?

### ISSUE THREAD

**Issue by kbsmth** [PeachScript/sketch-plugin-monster#19]
I have set custom keyboard shortcuts at my OS level that will often times conflict with the shortcuts defaulted by a plugin. Is there a way to check for conflicts among those?

Example: I use Cmd+Shift+] to move an object to the front. Sketch also uses this shortcut by default to align text to the right. Occasionally there is a discrepancy, but I have learned some of the quarks and try to avoid those situations.

**Comment by PeachScript** [comment]
I understood, it's a bug, this plugin will check for conflicts base on a Sketch shortcuts table when you press a new shortcut, I put `shift cmd {` and `shift cmd }` into this [shortcuts table](https://github.com/PeachScript/sketch-plugin-monster/blob/master/Sketch%20Plugin%20Monster.sketchplugin/Contents/Sketch/i18n/en.json#L108), but they should be `shift cmd [` and `shift cmd ]`, so it not work for this situation, I will fix it, thanks!

By the way, this plugin will prompt for you if your new shortcuts conflict with Sketch or other plugins but except your custom shortcuts in the OS X System Preferences.

**Comment by PeachScript** [comment]
Hi @kbsmth  , [`v0.3.0`](https://github.com/PeachScript/sketch-plugin-monster/releases/tag/v0.3.0) has been released, this problem should be solved, you can try it now :P
