### ISSUE TITLE
Shortcut manager stops showing up

### ISSUE THREAD

**Issue by freshlesh3** [PeachScript/sketch-plugin-monster#20]
After clicking the "Plugins Shortcut Management" menu the window doesn't appear.

**Comment by PeachScript** [comment]
What is the version of Sketch you are using?

**Comment by pykgg476** [comment]
I am having the same problem.
sketch version is 44.1.

**Comment by freshlesh3** [comment]
I'm using version 43.1

**Comment by PeachScript** [comment]
Perhaps it has something wrong when reading configuration of other plugins, could you paste the crash log in [Pastebin](https://pastebin.com/) or other website like it?

Steps:

1. Open `Sketch.app`;
2. Open `Console.app` in `Applications/Utilities` folder;
3. Type `sketch` in the search box at the top right of the window;
4. Click `Plugins Shortcut Management` from `Plugins` menu in `Sketch`;
5. Copy all output informations in the `Console.app` and paste them in the [Pastebin](https://pastebin.com/);
6. Save it and put the `Pastebin` link here.

**Comment by PeachScript** [comment]
Hi @freshlesh3 @pykgg476 , [`v0.3.0`](https://github.com/PeachScript/sketch-plugin-monster/releases/tag/v0.3.0) has been released, this problem should be solved, you can try it now :P
