### ISSUE TITLE
Conflict status problem of the plugin title

### ISSUE THREAD

**Issue by golevkadesign** [PeachScript/sketch-plugin-monster#21]
Plugin Monster提示有两个插件的快捷键冲突，于是我把其中一个的快捷键清除了，这时候显示绿色成功提示，但插件的标题还是红色的。

**Comment by PeachScript** [comment]
猜测你清除快捷键的那个插件不止一个冲突，所以即便你清除快捷键以后仍然会提示你插件冲突；严格来说这不是 bug 而是一个体验优化问题。
