### ISSUE TITLE
unsupported keys (Arrow keys)

### ISSUE THREAD

**Issue by RaphyRaph** [PeachScript/sketch-plugin-monster#23]
I'm trying to set control+[right arrow]

![screenshot 2017-05-25 14 53 15](https://cloud.githubusercontent.com/assets/3810802/26453002/132ce074-415a-11e7-8f01-e1fcffd076a4.png)

**Comment by PeachScript** [comment]
Aha, I always think arrow keys cannot be set as shortcut keys, I will fix it, thanks!

**Comment by PeachScript** [comment]
Hi @RaphyRaph , [`v0.3.0`](https://github.com/PeachScript/sketch-plugin-monster/releases/tag/v0.3.0) has been released, this problem should be solved, you can try it now :P

**Comment by RaphyRaph** [comment]
Resolved, thx!
