### ISSUE TITLE
Dosn't work with the ForeignIpsum plugin (manifest.json parsing error)

### ISSUE THREAD

**Issue by Nevu** [PeachScript/sketch-plugin-monster#28]
Hi!

Like I said — It doesn't work on Version 44.1. I hit manage or export, but nothin happened.

**Comment by PeachScript** [comment]
Perhaps it has something wrong when reading configuration of other plugins, could you paste the crash log in [Pastebin](https://pastebin.com/) or other website like it?

Steps:

1. Open `Sketch.app`;
2. Open `Console.app` in `Applications/Utilities` folder;
3. Type `sketch` in the search box at the top right of the window;
4. Click `Plugins Shortcut Management` from `Plugins` menu in `Sketch`;
5. Copy all output informations in the `Console.app` and paste them in the [Pastebin](https://pastebin.com/);
6. Save it and put the `Pastebin` link here.

Thanks!

**Comment by Nevu** [comment]
Ok — Thank you for these steps. I hope I did it right:  https://pastebin.com/6RSMr157

**Comment by PeachScript** [comment]
I see, there has some errors when parsing `mainfest.json` of some plugins. I will catch the errors in the next version, but now...if you don't mind, could you pack your `Plugins` folder and upload to a website like [file.town](https://file.town) to help me solve this problem?

**Comment by Nevu** [comment]
For sure!

Here is the Link: https://we.tl/LvKfE04u77
The folder is a little bit messy 😅

**Comment by PeachScript** [comment]
Haha, anyway, your `Plugins` folder already help me to find the real reason, thank you very much!

Because of I'm developing the `v0.3.0`, I cannot release a new version now, but you can try the [version under development](https://github.com/PeachScript/sketch-plugin-monster/archive/master.zip) from the latest master branch(perhaps you will see some strange things on the panel 🤐 ), and I will release the `v0.3.0` as soon as possible.

Best regards.

**Comment by PeachScript** [comment]
@Nevu [`v0.3.0`](https://github.com/PeachScript/sketch-plugin-monster/releases/tag/v0.3.0) has been released, you can try it now :P

**Comment by Nevu** [comment]
Thank you so muc! It works. And again: One of the greatest (smartes) Plugins I use :P

**Comment by PeachScript** [comment]
Thanks you for appreciation, make me very happy! 😆
