### ISSUE TITLE
Incompatibility with Lingo plugin

### ISSUE THREAD

**Issue by RaphyRaph** [PeachScript/sketch-plugin-monster#29]
Looks like Plugin Monster is causing issues with https://www.lingoapp.com. 

Screencap:
https://www.dropbox.com/s/tfxhnaib4i64w10/Lingo%20%26%20plugin%20monster.mov?dl=0

**Comment by golevkadesign** [comment]
Hey man, I have try to reproduce this issue according to your video(Plugin Monster V0.31 and LingoV3.3.2), and no problem occurred. I guess it's caused by the Lingo's beta version. Suggest you upgrade this APP to the latest version.  : )

**Comment by RaphyRaph** [comment]
Yep it works now.
