### ISSUE TITLE
Sketch V45 crashes on Runner 'run' command

### ISSUE THREAD

**Issue by oleh-konyk** [PeachScript/sketch-plugin-monster#30]
### Version
0.3.0

### Sketch version
v45

### What is exptected?
Sketch simply crashes when i try to run the Runner. Both through the menu and "cmd+'".

### The error log from `Console.app` when the problem occurred
https://pastebin.com/LmwKssu7

**Comment by PeachScript** [comment]
Yep, but the real reason is the `Runner` v0.9.1 and early are not compatible with `Sketch` 45, and now `Runner` v0.9.2 has been able to work with `Sketch` 45, so this issue was not caused by `sketch-plugin-monster` : )
