### ISSUE TITLE
Sketch Plugin Monster not working on Sketch 45.2

### ISSUE THREAD

**Issue by richardsison** [PeachScript/sketch-plugin-monster#32]
### Version
0.3.0

### Sketch version
45.2

### What is exptected?
The plugin's window to edit shortcuts should appear.

### What is actually happening?
Nothing happens.

### How to repreduce this problem?
try to

### The error log from `Console.app` when the problem occurred
https://pastebin.com/bFUcbhrD

**Comment by PeachScript** [comment]
Duplicate with #31 , I will fix it as soon as possible, thanks!
