### ISSUE TITLE
Plugin not loading

### ISSUE THREAD

**Issue by MeganGilligan1** [PeachScript/sketch-plugin-monster#40]
Sketch-plugin-monster version 4.0

Sketch version 50.2 

Plugin just not loading any time after opening
![image](https://user-images.githubusercontent.com/25102188/42095557-db151daa-7baa-11e8-91cb-93007daf08c6.png)

https://pastebin.com/MzPE7bEd

**Comment by PeachScript** [comment]
@MeganGilligan1 got it, I will fix it recently, thanks!

**Comment by PeachScript** [comment]
Hi @MeganGilligan1 , this problem has been fixed in the latest version `v0.4.1`, you can try it now :)

**Comment by MeganGilligan1** [comment]
Hi @PeachScript, I can't seem to find the sketch plugin file in the master folder for v0.4.1 

![image](https://user-images.githubusercontent.com/25102188/44043109-ec0c4fa6-9f19-11e8-91ae-448817f27977.png)

**Comment by PeachScript** [comment]
Please download from the [GitHub release page](https://github.com/PeachScript/sketch-plugin-monster/releases) or [other ways](https://github.com/PeachScript/sketch-plugin-monster#installation), the master branch only contains source code.

**Comment by PeachScript** [comment]
@MeganGilligan1 I'm so sorry, I forgot to upload the release file so you cannot download it before, now it is available: https://github.com/PeachScript/sketch-plugin-monster/releases
