### ISSUE TITLE
Can't update to 0.4.1

### ISSUE THREAD

**Issue by aparajita** [PeachScript/sketch-plugin-monster#42]
### Version
0.4.1

### Sketch version
51.2

### What is expected?
Clicking "Update" button in Sketch plugins pane or in Runner updates the plugin.

### What is actually happening?
Nothing.

### How to repreduce this problem?
Try updating from 0.4.0.

### The error log from `Console.app` when the problem occurred
Not necessary. It isn't working because you neglected to add the plugin archive to the release. It's that simple.

**Comment by PeachScript** [comment]
@aparajita oh sorry, it's my mistake, I will upload it now, thanks for your report!

**Comment by PeachScript** [comment]
@aparajita it is available now, thanks again!

**Comment by aparajita** [comment]
FYI installing 0.4.2 via Runner fails.

**Comment by PeachScript** [comment]
It's a known problem #41 , we are in contact with Runner team to get a debug way.
